"""all models creation

Revision ID: 083a2a0fa473
Revises: 
Create Date: 2026-08-02 22:02:57.473204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083a2a0fa473'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specializations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spheres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=45), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('result', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_position_id'), 'interviews', ['position_id'], unique=False)
    op.create_index(op.f('ix_interviews_specialization_id'), 'interviews', ['specialization_id'], unique=False)
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    op.create_table('subspheres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sphere_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sphere_id'], ['spheres.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subspheres_sphere_id'), 'subspheres', ['sphere_id'], unique=False)
    op.create_table('interview_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('raw_ai_response', sa.Text(), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('general_feedback', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('action_plan', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_reviews_interview_id'), 'interview_reviews', ['interview_id'], unique=True)
    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('main_ai_prompt', sa.Text(), nullable=False),
    sa.Column('current_step_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_interview_id'), 'interview_sessions', ['interview_id'], unique=True)
    op.create_table('interview_spheres',
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('sphere_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sphere_id'], ['spheres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interview_id', 'sphere_id')
    )
    op.create_index(op.f('ix_interview_spheres_sphere_id'), 'interview_spheres', ['sphere_id'], unique=False)
    op.create_table('interview_subspheres',
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('subsphere_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subsphere_id'], ['subspheres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interview_id', 'subsphere_id')
    )
    op.create_index(op.f('ix_interview_subspheres_subsphere_id'), 'interview_subspheres', ['subsphere_id'], unique=False)
    op.create_table('interview_topics',
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interview_id', 'topic_id')
    )
    op.create_index(op.f('ix_interview_topics_topic_id'), 'interview_topics', ['topic_id'], unique=False)
    op.create_table('subsphere_specializations',
    sa.Column('subsphere_id', sa.Integer(), nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subsphere_id'], ['subspheres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subsphere_id', 'specialization_id')
    )
    op.create_index(op.f('ix_subsphere_specializations_specialization_id'), 'subsphere_specializations', ['specialization_id'], unique=False)
    op.create_table('session_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_session_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('raw_ai_question', sa.Text(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('importance_level', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_session_id', 'number', name='uq_session_steps_session_number')
    )
    op.create_index(op.f('ix_session_steps_interview_session_id'), 'session_steps', ['interview_session_id'], unique=False)
    op.create_table('code_writing_questions',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('base_code', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['session_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theoretical_questions',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['session_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_step_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=45), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_step_id'], ['session_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_answers_session_step_id'), 'user_answers', ['session_step_id'], unique=True)
    op.create_table('answer_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_answer_id', sa.Integer(), nullable=False),
    sa.Column('raw_ai_feedback', sa.Text(), nullable=False),
    sa.Column('response_in_session', sa.Text(), nullable=False),
    sa.Column('feedback_in_review', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_answer_id'], ['user_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_feedbacks_user_answer_id'), 'answer_feedbacks', ['user_answer_id'], unique=False)
    op.create_table('code_writing_answers',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theoretical_answers',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theoretical_answers')
    op.drop_table('code_writing_answers')
    op.drop_index(op.f('ix_answer_feedbacks_user_answer_id'), table_name='answer_feedbacks')
    op.drop_table('answer_feedbacks')
    op.drop_index(op.f('ix_user_answers_session_step_id'), table_name='user_answers')
    op.drop_table('user_answers')
    op.drop_table('theoretical_questions')
    op.drop_table('code_writing_questions')
    op.drop_index(op.f('ix_session_steps_interview_session_id'), table_name='session_steps')
    op.drop_table('session_steps')
    op.drop_index(op.f('ix_subsphere_specializations_specialization_id'), table_name='subsphere_specializations')
    op.drop_table('subsphere_specializations')
    op.drop_index(op.f('ix_interview_topics_topic_id'), table_name='interview_topics')
    op.drop_table('interview_topics')
    op.drop_index(op.f('ix_interview_subspheres_subsphere_id'), table_name='interview_subspheres')
    op.drop_table('interview_subspheres')
    op.drop_index(op.f('ix_interview_spheres_sphere_id'), table_name='interview_spheres')
    op.drop_table('interview_spheres')
    op.drop_index(op.f('ix_interview_sessions_interview_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_interview_reviews_interview_id'), table_name='interview_reviews')
    op.drop_table('interview_reviews')
    op.drop_index(op.f('ix_subspheres_sphere_id'), table_name='subspheres')
    op.drop_table('subspheres')
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_specialization_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_position_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('topics')
    op.drop_table('spheres')
    op.drop_table('specializations')
    op.drop_table('positions')
    # ### end Alembic commands ###
